### ISSUE TITLE
STRchive: A database of STRs associated with disease in humans.

### ISSUE THREAD

**Issue by hdashnow** [CU-DBMI/set-intake#11]
### Group

Dashnow Lab

### Contact info

Harriet Dashnow (she), PI, harriet.dashnow@cuanschutz.edu, Harriet Dashnow on Slack
Laurel Hiatt (they/he), project lead, MD/PhD student at U of Utah, Laurel.Hiatt@hsc.utah.edu 

### Links to code

Website: https://strchive.org/
Code/data: https://github.com/dashnowlab/STRchive
Preprint: https://www.medrxiv.org/content/10.1101/2024.05.21.24307682v1

### Workflow

- Git/GitHub
- OSX/Linux HPC
- Python, R, conda, semantic-ui (but open to changing)
- VScode, R studio, vim

### Work description

STRchive is a website that presents a JSON database of disease loci in a format that is easy to view on the web. Behind the scenes, the data can be downloaded and used in research and clinical workflows, e.g., variant filtering/prioritization. We also have population frequency data sourced from gnomAD and HPRC which is not yet presented on the website. 
I have created a basic website to present the data using semantic-ui, but I am not a web developer and I think there is vast scope for improvement.

Scope of work:
Revamp the website to make it more beautiful and user-friendly (either using the existing framework or another that you prefer, as long as it's easy for us to update). Specifically:
- Improve overall look/design
- Better use of color and other visual features to distinguish quality of evidence
- Add search/filter/sort to the table https://strchive.org/database/index.html
- Add static and/or interactive graphs to individual gene pages showing population data. Here's a motivating example from our collaborator, Ben: https://gnomad.broadinstitute.org/short-tandem-repeat/HTT?dataset=gnomad_r3
- Make additional database content available on the website and potentially add some new fields.
- Add automated literature retrieval e.g. with Actions

Other information:
- HIPPA: no, all the data we're using here is from public databases and academic publications. Population data is from gnomAD/1000g/HPRC, which are all public.
- Platforms: Web browsers for desktop and mobile. Code in Linux environment.
- We'd love help automating some of the maintenance tasks. For example, GitHub Actions running a script every month that pulls recent publications and notifies maintainers to check for updates.

### Timeline

My best case would be to scope out a minimum viable product to release in late October or November to coincide with a paper resubmission, then add additional features over a longer timeframe. I'd love your feedback on what is reasonable. 

### Funding

We have funds available to support this work through grants and/or start-up

**Comment by vincerubinetti** [comment]
Hi Harriet,

Sorry it's taken me this long to get back to you on this. This is right in our wheel house and seems relatively small scope. We should have availability for it in general, but it may be hard to get done before the end of Oct with our other commitments (even if we had responded right when you requested this).

Could you schedule a meeting with us using our booking page below so we could briefly chat about the strategy here?
https://outlook.office365.com/book/SoftwareEngineeringTeam@olucdenver.onmicrosoft.com/

This booking page conveniently lists the times that all members of the software team are available, but if you need more availability, only Faisal and I really need to be present, so you could use our Outlook calendars (vincent.rubinetti@cuanschutz.edu and faisal.alquaddoomi@cuanschutz.edu).

**Comment by hdashnow** [comment]
Thanks @vincerubinetti! I look forward to chatting next week when I'm back in the US.

**Comment by vincerubinetti** [comment]
I forgot to mention, please also invite anyone who worked on the existing site, so we can discuss technical details. Looks like that would include Laurel. I believe you should have control over the meeting invite to add new people. If not, please forward the calendar invite to them.

**Comment by vincerubinetti** [comment]
I think we've met all these (with the exception of the automations) as of writing on https://github.com/dashnowlab/STRchive/tree/strchive-v2
