### ISSUE TITLE
Administer Coding Exercise - Postdoc candidate

### ISSUE THREAD

**Issue by jcole150** [CU-DBMI/set-intake#8]
### Group

Cole Lab

### Contact info

Joanne Cole, PI, <joanne.cole@cuanschutz.edu>

### Work description

Administer coding exercise to postdoc candidate. 

### Timeline

The candidate's full on-campus interview is 1/10. It would be preferable to schedule this in the first two weeks of January.

**Comment by d33bs** [comment]
Thank you @jcole150 for sending this request along! I've followed up in an email to you.

**Comment by d33bs** [comment]
Thank you @jcole150 for letting us assist! Please don't hesitate to let us know if you have any questions. Closing this issue out for now.
